apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-nodeapp
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/test-nodeapp@sha256:9a2cb1a11528ce53ea766832496e90cfb15ea6dc8061182bc2e1dc66a9c6c850
        name: container-image
        resources: {}
status: {}
